### ISSUE TITLE
Testing zlib fails

### ISSUE THREAD

**Issue by bronikowski** [rss2email/rss2email#144]
By accident I filled an issue with a fork while I'm using this version, hope linking stuff like that is OK:

https://github.com/wking/rss2email/issues/123

**Comment by Ekleog** [comment]
No problem! Actually, historically speaking this repo is a fork of the wking one, but maintainership moved over to here quite a while ago now and the wking one hasn't seen changes for 4-5 years IIRC :)

If I understand correctly, your issue is due to the feedparser 6.0.0 upgrade, and is solved by rolling back to the latest 5.x series version, is that correct? If so, this is currently known (feedparser 5.x and 6.x are incompatible, so we can reasonably work with only one of the two), and 6.0.0 was released just a few days ago (following a poke by your servitor, if I may :stuck_out_tongue_winking_eye:), so we haven't had enough time to migrate yet — this work is being tracked at https://github.com/rss2email/rss2email/issues/73 .

That said, I'm surprised this was an issue, as our requirements.txt already explicitly states `feedparser==5.2.1`, so I'd have expected pip to not try feedparser 6.0.0.

Does my answer address your question?

**Comment by bronikowski** [comment]
> If I understand correctly, your issue is due to the feedparser 6.0.0 upgrade, and is solved by rolling back to the latest 5.x series version, is that correct?

Yes, I locked it in my provisioning.

> That said, I'm surprised this was an issue, as our requirements.txt already explicitly states feedparser==5.2.1, so I'd have expected pip to not try feedparser 6.0.0.

That's interesting. Let me check it on my end.

Ah, maybe it's because I'm doing `git+ssh` in my pip install? I remember having problem with it not pulling proper dependencies. So it's kinda self-inflected wound. Heh. Well, since you already know about the issue and your requirements.txt is up to snuff I guess I just cried wolf for no reason.

**Comment by Ekleog** [comment]
No problem, and thank you for your report anyway! We could not have known about it :)

**Comment by auge** [comment]
sorry to comment on a close issue:
in the release 3.12 (the latest one on pypi), the [setup.py](https://github.com/rss2email/rss2email/blob/release-3.12/setup.py) specifies 'feedparser>=5.0.1'
pip will use the setup.py file (and not the requirements.txt file) and therefore will happily use the broken feedparser version ...

**Comment by Ekleog** [comment]
@auge Hopefully this should be solved with 3.12.3. Can you confirm that it works for you? (with a version of python that predates 3.9, as only current-master works with python 3.9+)

**Comment by auge** [comment]
@Ekleog the requirements section is fixed; I've also installed and tested the version.
everything is fine!
(tested on Python 3.8.8 and 3.9.2)

**Comment by Ekleog** [comment]
Great, thank you for the confirmation :) hopefully 3.13 should come out soon with an updated feedparser, which should bring in years of improvements there
