### ISSUE TITLE
[SOLVED] incorrectly declared encoding: document declared as us-ascii, but parsed as utf-8

### ISSUE THREAD

**Issue by auouymous** [rss2email/rss2email#179]
3.13 now uses the verbose setting and will display warnings when run from cron or console. The `incorrectly declared encoding: document declared as us-ascii, but parsed as utf-8` warning is a problem with the feed that only the feed owner can fix. It doesn't appear to cause any problems and non-ASCII characters render fine in emails. Anyone with this issue must ignore it, set `verbose = error` or contact the feed owner.

https://validator.w3.org/feed/ will show the same warning.

https://pythonhosted.org/feedparser/character-encoding.html clearly explains the problem and how to fix it.

**Comment by amiryal** [comment]
The change in default logging level has been discussed here before:
> When setting up rss2email for the first time it's quite confusing that nothing gets logged. User starts to wonder, especially on first run which may take a while, _"what is happening? did it hang?"_. Once the user likes rss2email (and note that lack of app feedback might be discouraging) and is comfortable with rss2email there is still an option to reduce logging.
> — @jpalus https://github.com/rss2email/rss2email/issues/163#issuecomment-812453616

I am wondering if it would make sense, to revert the default to be more quiet (i.e. for cron jobs and systemd timers), but if `sys.stdin.isatty()` (i.e. when running in a terminal) then increase verbosity to a minimum of `info` unless `--no-verbose` is specified on the command line.

**Comment by amiryal** [comment]
Thanks for the info about this `incorrectly declared encoding` warning, BTW; I have seen it in my logs, too.

**Comment by Ekleog** [comment]
Hmm so I wouldn't feel good making the default behavior differ significantly between tty output and cron output: while colors changing are “normal stuff”, entirely removing log lines would IMO be surprising and possibly cause lots of weird-to-understand problems to users. So I think that the default verbosity should be set as a simple value.

Overall, this is probably a one-time change for users of systemd timers or cron: it's enough to add one line to the config file to fix it if they preferred the silent behavior. But now at least they'll know that they don't get the warnings, if they want to avoid the warning linked here :)

That being said, it might make sense to have the default level be warning… but then it wouldn't help with the issue linked here; and given that 3.14 will probably be at least a few months away I'm not sure it makes sense to make people change their configuration twice.

We _could_ release 3.14 right now that'd change the default to be warning instead of error (IMO the default being error was definitely wrong), but… I'm not sure it'd help that much, especially if a significant number of feeds are incorrectly declared as ascii?

Anyway, @auouymous, thank you for opening this issue! It'll probably help other people understand what's going on when they see the new warning message that was previously hidden :)

**Comment by auouymous** [comment]
I agree with @jpalus about defaulting to info. But we could help users out by displaying an info message about changing verbose to warning or error. And maybe change 1-2 of the three info messages per feed to debug messages. Some of them seemed redundant.

**Comment by jpalus** [comment]
To reiterate I think it's fine logging works now and I don't see anything wrong with neither info, nor warning messages being present. I wouldn't be surprised if long term users start complaining about it though -- some projects even treat long term bugs as "behavior users rely on" :). However there are two things worth considering:
* perhaps adding universally recognized flag '-q' for quiet mode? (error level effectively)
* having all output going to stderr is somewhat problematic as the other common way to deal with unwanted logging is redirecting it to /dev/null, `r2e run > /dev/null` doesn't work and `r2e run 2> /dev/null` swallows real errors. I think it would be good to have ERROR on stderr and rest on stdout

**Comment by Ekleog** [comment]
Closing as the discussion is going on in #180
