### ISSUE TITLE
Make it explicit why this new repo is preferred over wking/rss2email

### ISSUE THREAD

**Issue by olberger** [rss2email/rss2email#18]
In https://github.com/wking/rss2email/issues/105 someone suggested to redirect people to here... but AFAICS there's no clear explanation why this is the new canonical home of rss2email (I couldn't trace a fork in GitHub ?).

What's the current status ?

Thanks in advance.

**Comment by jsbackus** [comment]
Hi @olberger, good question! The goal was to move the project to an organization in order to make it easier to 'pass the torch' in the event someone gets so overloaded by life that they are unable to contribute, much like what has happened to @wking. And of course, before we could really get off the ground, demands in my life changed and left little time for this project.

The lack of fork was intentional. The goal is for this project to be the 'root of forks'. We've incorporated work from @wking as well as several other contributors. 

I've put a rough outline for a plan in #19. Please let me know if you have any additional questions/comments/concerns.

**Comment by Profpatsch** [comment]
See https://github.com/rss2email/rss2email/issues/19 and https://github.com/rss2email/rss2email/issues/28
