### ISSUE TITLE
Warning "looks like HTML" and HTTP status 304

### ISSUE THREAD

**Issue by xrat** [rss2email/rss2email#189]
I had just upgraded to rss2email 3.13.1 and feedparser 6.0.3. Now I get the `[WARNING] looks like HTML` for some feeds, and I wonder why because when I run them very verbosely it says

```
[DEBUG] HTTP status 304
[DEBUG] HTTP headers: {'cross-origin-resource-policy': 'cross-origin', 'etag': 'W/"d986a8237319d44b834b96eb7b266b145c69875be236d925d6b6fc48adab9936"', 'date': 'Sun, 13 Jun 2021 17:54:01 GMT', 'content-type': 'text/html', 'server': 'blogger-renderd', 'expires': 'Sun, 13 Jun 2021 17:54:02 GMT', 'cache-control': 'public, must-revalidate, proxy-revalidate, max-age=1', 'x-content-type-options': 'nosniff', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'connection': 'close'}
[WARNING] looks like HTML: dnsbl.com (https://www.dnsbl.com/feeds/posts/default -> ...)
```

Isn't this warning futile in case of HTTP status 304?

**Comment by auouymous** [comment]
I'm not having any issues with r2e 3.13.1 and feedparser 6.0.3.

Whenever a site is down for maintenance all URLs, including feeds, display a static HTML page. The second debug line clearly indicates the content is text/html and therefore it doesn't matter what the status code is, it is currently not a valid RSS feed. The issue will most likely be resolved on your next run, unless you do hourly updates.

**Comment by xrat** [comment]
I am not having "issues". I think that r2e should ignore data after 304, hence the warning is futile.

**Comment by auouymous** [comment]
I disagree, the warning is working as intended and concealing it would be wrong. A feed could be replaced with a page pointing to the feed's new home, and you would never know this if r2e was hiding the warning.

The issue here is that the warning (and other warnings and errors) are terrible for anyone who isn't an r2e developer. It could better indicate the feed appears to be an HTML web page instead of a valid RSS feed, and that it is probably transient but if it persists, the user should visit the feed URL.

**Comment by xrat** [comment]
I do not disagree but I also do not see how your comment relates to HTTP status 304 (not modified).

**Comment by auouymous** [comment]
r2e saves the current time when it updates a feed. On the next update, it sends the previous time to the server when requesting the feed. If the content has not been updated since that time, the server returns a 304 instead of the feed data.

The server sends a web page for all URLs during maintenance and other issues. This page will either be newer or older than the timestamp r2e sends in the request. It sends content with a 200 status if newer, or it sends a 304 and no content if older. In either case, r2e throws a "looks like HTML" warning.

Ignore the 304 and debug messages, the warning is simply telling you something is wrong with the feed.

**Comment by xrat** [comment]
I don't think there was anything wrong with this particular feed. But indeed things changed since yesterday, and I cannot reproduce the warning.

**Comment by JulienPalard** [comment]
I'm having the exact same issue, on blogger too, on https://mypy-lang.blogspot.com/feeds/posts/default

As they don't post often is easy to reproduce.

**Comment by xrat** [comment]
@JulienPalard FWIW, I edited my https://github.com/rss2email/rss2email/blob/a54089bb83ab67e09bbc5312e8e0618ba897e4ae/rss2email/feed.py#L424 to ignore HTTP status 304, i.e.
`if ('html' in http_headers.get('content-type', 'rss') and not status in [304]):`

**Comment by auouymous** [comment]
It would be better if you ran r2e with `verbose = error` and once a week have cron call it with `-V` to see warnings. Otherwise you won't know if the feed is redirecting to a "feed no longer exists" page.
