### ISSUE TITLE
ResourceWarning: unclosed file

### ISSUE THREAD

**Issue by JulienPalard** [rss2email/rss2email#204]
Using the environment variables:

    PYTHONDEVMODE=1
    PYTHONTRACEMALLOC=10

I get:

```bash
$ r2e list
0: [*] discourse (https://blog.discourse.org/feed.xml -> julien@palard.fr)
bin/r2e:8: ResourceWarning: unclosed file <_io.BufferedReader name='/home/mdk/.local/share/rss2email.json'>
  sys.exit(run())
Object allocated at (most recent call last):
  File "bin/r2e", lineno 8
    sys.exit(run())
  File "rss2email/main.py", lineno 199
    feeds.load()
  File "rss2email/feeds.py", lineno 233
    self._load_feeds(require=require)
  File "rss2email/feeds.py", lineno 248
    self.datafile = _codecs.open(
  File "/usr/lib/python3.9/codecs.py", lineno 905
    file = builtins.open(filename, mode, buffering)
```

**Comment by amiryal** [comment]
Interesting, but `r2e` is not a long-running daemon process, so I think it can be safely ignored in this case. WDYT?

**Comment by amiryal** [comment]
@auouymous you said you were:
> […] looking into a fix for #204

I think a very simple procedure would be, since `feeds.load()` opens the file and `feeds.save_feeds()` closes it, to call both of them from the same scope. I.e. to remove this:
https://github.com/rss2email/rss2email/blob/9f74b81e179fcf37d8cfc1c0ff2dd34859be622b/rss2email/main.py#L198-L199
…and sprinkle `feeds.load()`s all over the methods in `rss2email/command.py` that call `feeds.save_feeds()`.

A slightly more invasive operation would be to turn `feeds.load()` into a context manager that calls `feeds.save_feeds()` by itself.

**Comment by auouymous** [comment]
A simpler approach is to add a feeds.close() method, call it from save_feeds() and after args.func(). That way any commands (list, pause, unpause and opmlexport) that don't call save_feeds() will close the file.

**Comment by JulienPalard** [comment]
In one hand I fully agree that for this kind of process, not closing files is not an issue. The issue for me is I use PYTHONDEVMODE, mainly to find DeprecationWarnings and other things like that, and unclosed file pollute my daily life, so I also try to close them, or at least open an issue when I find one.

(willing to fix it I found https://github.com/rss2email/rss2email/pull/203 so I opened it first :D)
