### ISSUE TITLE
Is there a way to convert from the old feeds.dat system to the new JSON system?

### ISSUE THREAD

**Issue by arinoch** [rss2email/rss2email#258]
Previous OS I was on had rss2email as a package, and that version created config.py and feeds.dat files in a .rss2email directory. This version doesn't do that, which I can definitely work with. I've copied my configuration data over to the new file, but is there a way that I can pull the feeds out of feeds.dat and import them into the JSON version? I do not have the old version of RSS2Email to perform an OPML export, but if I need to I can probably find that version.

**Comment by auouymous** [comment]
Are you good with sed or any scripting languages? If so, it should be easy to find the feed URLs in the dat file, split each one to its own line, trim the URLs and then wrap in OPML syntax.

Otherwise you will need to find the old binary, or download the repo `git clone https://github.com/rss2email/rss2email.git`, change to the directory it downloads, run `git checkout v2.71` and then run r2e from that directory.

**Comment by arinoch** [comment]
I was afraid you might say that, so I just did it by hand. Took me a little over an hour but I think I'm good.
