### ISSUE TITLE
Make official sources point to this repo

### ISSUE THREAD

**Issue by Profpatsch** [rss2email/rss2email#28]
None of
- [x] https://pypi.python.org/pypi/rss2email
- [ ] http://www.allthingsrss.com/rss2email/
- [ ] https://tracker.debian.org/pkg/rss2email

point to this repository for a rss2email home, yet. Would be awesome to get that fixed so people don't need to find things like https://github.com/wking/rss2email/issues/97 to get an answer to where to go to for the latest. Thanks!

_Originally posted by @hartwork in https://github.com/rss2email/rss2email/issues/3#issuecomment-357793063_

**Comment by Profpatsch** [comment]
Opened issues in 

https://github.com/turbodog/rss2email/issues/12
https://github.com/Dieterbe/rss2email/issues/2

and added a reminder to https://github.com/wking/rss2email/issues/105 that we are progressing in this repo.

**Comment by Ekleog** [comment]
I think changing the links on http://www.allthingsrss.com/rss2email/ will be hard, given it appears to be a personal wordpress that hasn't been updated since 2011, so I guess we can give up on that. I'll try to contact debian to get them to change the homepage.

I've turned the top post in checkboxes so that we can check them one by one as we have done all we can to fix them up, and checked the allthingsrss.com one, and will check the debian tracker one once I get an answer.

**Comment by Ekleog** [comment]
I've contacted the debian maintainer, so I guess things are now out of our hands for this matter.

Now, let's figure out how to change the homepage on pypi.org… I wonder whether that actually requires a new release, as I can find no web interface to do that.

**Comment by gfa** [comment]
is there any release coming soon?

**Comment by gfa** [comment]
I see commits to master, is the release coming soon? the package will be removed from Debian testing soon
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=935800

**Comment by Profpatsch** [comment]
> the package will be removed from Debian testing soon

How soon is soon? We were thinking about doing another point-release. Though I don’t know whether our current master solves the problem for Debian. Can you test?

**Comment by Ekleog** [comment]
This issue should have been fixed by https://github.com/rss2email/rss2email/pull/64 ; we need https://github.com/rss2email/rss2email/issues/2 to be fixed so that the manpage is up-to-date with the code before the next release.

Maybe either debian could use the patch from #64 or someone could help with #2, so that we could cut the release?

**Comment by nikaro** [comment]
It looks like this issue can be closed.

[x] PyPI
[x] Debian
[ ] ~AllThingsRSS~ (DNS name is not resolved anymore)

**Comment by Ekleog** [comment]
Indeed, thank you :)
