### ISSUE TITLE
Reach out Linux distros that may be using older versions

### ISSUE THREAD

**Issue by jsbackus** [rss2email/rss2email#4]
I know Fedora is using a pre-python3 version... Others?

**Comment by the0** [comment]
I've updated ArchLinux package and marked others as out-of-date: https://aur.archlinux.org/packages/?O=0&SeB=nd&K=rss2email&outdated=&SB=n&SO=a&PP=50&do_Search=Go

**Comment by fszymanski** [comment]
My Fedora Copr repo: https://copr.fedorainfracloud.org/coprs/fszymanski/rss2email/

**Comment by hartwork** [comment]
Just updated Gentoo to lastest Git HEAD — https://github.com/gentoo/gentoo/commit/8a03252d776c454d0cc0feb85f54830bfdd6e178

**Comment by hartwork** [comment]
For finding other out-of-date packages, this repology.org page be of help:
https://repology.org/metapackage/rss2email/versions

**Comment by olberger** [comment]
Debian's "homepage" attribute seems to point to https://github.com/wking/rss2email as per https://tracker.debian.org/pkg/rss2email. Haven't check with the maintainer though.

**Comment by thomasjfox** [comment]
Fedora used to track the v3.x migration here:
https://bugzilla.redhat.com/show_bug.cgi?id=911509

The v3.9 source rpm from Michael Schwendt also features a v2.x -> v3.x migration script
from Etienne Millon (Debian):
https://bugzilla.redhat.com/show_bug.cgi?id=911509#c15

**Comment by kaashif** [comment]
In case anyone is interested, I tried to make a port for the new version in OpenBSD, see the messages here: https://marc.info/?l=openbsd-ports&m=151285481902867&w=2. It was over a year ago, actually.

It's a new package and not a straight upgrade since going from 2.70 to 3.9 breaks everything, and there are several rss2email users among the OpenBSD developers who aren't happy with that. Also, several people commented that the old version works better, with fewer bugs than the new version. This is probably still true, I think, there are lots of unreleased bug fixes floating around.

**Comment by kaashif** [comment]
The OpenBSD package is now updated to 3.10: http://openports.se/mail/rss2email

**Comment by gfa** [comment]
Debian ships code from this repo since 3.11, see Debian bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944358

**Comment by Ekleog** [comment]
I've just run over repology, and contacted the distributions that are running versions before 3.11 whose name at least ringed a bell, so may have missed some distributions but at least the major ones should be aware.

Let's close this, as it's now done as best as it could :)
