### ISSUE TITLE
Copy still valid issues from wkings repository

### ISSUE THREAD

**Issue by Profpatsch** [rss2email/rss2email#41]
https://github.com/wking/rss2email/issues still has 42 (noice) open issues at the time of this comment. We should go through them and see which ones are valid, comment and maybe open a copy here.

**Comment by Ekleog** [comment]
I've just poked every open issue to let them know the old repo is outdated and ask them to reopen the issue here if it's still relevant, this should probably be enough to reasonably say that all issues that still have stakeholders will be ported here, and issues that no one knows how to trigger any longer probably are not worth the time fixing them compared to the issues we know we have today. Closing as a consequence :)
