### ISSUE TITLE
Should ignore unknown config keys

### ISSUE THREAD

**Issue by jsbackus** [rss2email/rss2email#8]
Might want to issue a warning so that the user knows what is going on, but we shouldn't bail.

**Comment by kaashif** [comment]
Actually, isn't this a bad idea? If a config key changes name after an upgrade, the user might not notice if we just warn, meaning the key will take the default value. This could lead to crashing due to the config key having the wrong value when the _real_ problem was that the key name has changed. I would personally close this issue since I think the current behaviour is correct. @Ekleog @Profpatsch ? I guess since this isn't already addressed, you must agree the current behaviour is good.

**Comment by Ekleog** [comment]
This is, to me, a dual-edged sword:
* With ignore-unknown-config-keys, we can have config files be backwards-compatible with older rss2email versions, and thus adding a config key needs only a patch (and not a minor) version bump
* Without ignore-unknown-config-keys, we have that nice “key typo is easily noticed” feature.

Overall I think I agree with you that it's better not to have the ignore-unknown-config-keys behaviour :)

**Comment by kaashif** [comment]
Great, I'll just close this then.
