### ISSUE TITLE
r2e run fails for https sites

### ISSUE THREAD

**Issue by jpjoines** [rss2email/rss2email#92]
I'm using rss2email 3.11 with Python 3.8.1 and OpenSSL 1.1.1d on Ubuntu linux.  I get SSL: CERTIFICATE_VERIFY_FAILED errors with feeds on https sites:
$ r2e run --no-send
2020-01-31 18:06:06,734 [ERROR] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>: 1 (https://dynamicecology.wordpress.com/feed -> myemail)
2020-01-31 18:06:06,770 [ERROR] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>: 2 (https://dynamicecology.wordpress.com/comments/feed -> myemail)
2020-01-31 18:06:12,527 [ERROR] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)>: 12 (https://www.amnat.org/rss.xml -> myemail)
2020-01-31 18:06:12,945 [ERROR] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>: 13 (https://rss.sciencedirect.com/publication/science/01689525 -> myemail)
$

        The non-SSL feeds seem to work just fine:
$ r2e list
0: [*] 0 (http://investigadoresacg.org/blog/?feed=rss2 -> myemail)
1: [*] 1 (https://dynamicecology.wordpress.com/feed -> myemail)
2: [*] 2 (https://dynamicecology.wordpress.com/comments/feed -> myemail)
3: [*] 3 (http://investigadoresacg.org/blog/?feed=comments-rss2 -> myemail)
4: [*] 4 (http://www.nimbios.org/wordpress-training/selection/feed/ -> myemail)
5: [*] 5 (http://connect.biorxiv.org/biorxiv_xml.php?subject=bioinformatics -> myemail)
6: [*] 6 (http://connect.biorxiv.org/biorxiv_xml.php?subject=ecology -> myemail)
7: [*] 7 (http://connect.biorxiv.org/biorxiv_xml.php?subject=evolutionary_biology -> myemail)
8: [*] 8 (http://connect.biorxiv.org/biorxiv_xml.php?subject=genetics -> myemail)
9: [*] 9 (http://connect.biorxiv.org/biorxiv_xml.php?subject=genomics -> myemail)
10: [*] 10 (http://connect.biorxiv.org/biorxiv_xml.php?subject=paleontology -> myemail)
11: [*] 11 (http://connect.biorxiv.org/biorxiv_xml.php?subject=plant_biology -> myemail)
12: [*] 12 (https://www.amnat.org/rss.xml -> myemail)
13: [*] 13 (https://rss.sciencedirect.com/publication/science/01689525 -> myemail)
$

        Any ideas

**Comment by kaashif** [comment]
I can't reproduce this, but I'm on a completely different OS, so that doesn't say much. Can you connect to the problematic sites with e.g. `curl` or `wget` without errors?

To load certificates, we rely on the default behaviour of the `ssl.create_default_context` function, which creates the context and calls `load_default_certs`, which is documented [here](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.load_default_certs). This should pick up all of the certs from your system. On Ubuntu, a package that has a lot of common certificates is `ca-certificates`, but you probably already have that, I imagine.

If you can verify that you have all of the right CA certificates for those sites and they're in the default system location (probably `/usr/share/ca-certificates` on Ubuntu), then I think there might be something weird going on with `load_default_certs` - maybe it's not looking in the right place for whatever reason.

**Comment by kaashif** [comment]
Note: we actually don't check whether loading certificates succeeds since there isn't a real way to check this in the Python ssl API, no error is thrown if loading certificates fails. I guess one way to mitigate this would be to bundle our own CA certs with e.g. certifi, but then you have to trust something extra. And worse, we might trust certs that the system doesn't trust. There was some discussion about this in [PEP 476](https://www.python.org/dev/peps/pep-0476/#trust-database).

**Comment by jpjoines** [comment]
I can connect to the sites with wget.  I do have ca-certificates installed.  The individual certificates provided by that package are in subdirectories of /usr/share/ca-certificates and have the .crt file extension.  All of those certificates get concatenated to create the file /etc/ssl/certs/ca-certificates.crt.  They also get individually symlinked to files in /etc/ssl/certs with the .pem file extension.

        I can verify the certificates using OpenSSL if I call it using /etc/ssl/certs as the CA path:
openssl s_client -CApath /etc/ssl/certs/ -showcerts -connect rss.sciencedirect.com:443

ONNECTED(00000003)
depth=2 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO ECC Certification Authority
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO ECC Domain Validation Secure Server CA 2
verify return:1
depth=0 OU = Domain Control Validated, OU = PositiveSSL Multi-Domain, CN = ssl866934.cloudflaressl.com
verify return:1

        However, I get a "verify error:num=20:unable to get local issuer certificate" if I use /usr/share/ca-certificates or its subdirectories as the CA path:

openssl s_client -CApath /usr/share/ca-certificates/ -showcerts -connect rss.sciencedirect.com:443              
CONNECTED(00000003)
depth=2 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO ECC Certification Authority
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO ECC Domain Validation Secure Server CA 2
verify return:1
depth=0 OU = Domain Control Validated, OU = PositiveSSL Multi-Domain, CN = ssl866934.cloudflaressl.com
verify return:1

**Comment by jpjoines** [comment]
I think the problem was that neither the version of OpenSSL provided by the old Ubuntu version I am using, nor the new version of OpenSSL that I built from source expected the certificates to be in /etc/ssl/certs or /usr/share/ca-certificates/.  Rather than rebuilding OpenSSL, I symlinked  /usr/local/ssl/certs to /etc/ssl/certs and now r2e run does not return any erros.

**Comment by kaashif** [comment]
Fantastic! I'm glad your issue is solved and I'll improve the error checking when we create the SSL context - it would be great if instead of this cryptic error, you had seen "couldn't find certs in /usr/share/ca-certificates, please make sure they're there" or something like that.

**Comment by jpjoines** [comment]
Thanks for your help!
